### ISSUE TITLE
Splitter/consolidator worker encountered exception while consuming source data

### ISSUE THREAD

**Issue by luanmacek** [dotnet/machinelearning-samples#1026]
`ITransformer trainedModel = pipeline.Fit(_trainDataView);`

**Splitter/consolidator worker encountered exception while consuming source data**

ex.InnerException.Message
**Access to the path 'C:\300\Ok' is denied.**

   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.ML.Data.ImageLoadingTransformer.Mapper.TryLoadDataIntoBuffer(String path, VBuffer`1& imgData)
   at Microsoft.ML.Data.ImageLoadingTransformer.Mapper.<>c__DisplayClass5_0.<MakeGetterVectorDataViewByteType>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1.Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass7_1.<ConsolidateCore>b__2()

**Comment by luanmacek** [comment]
For some reason it wants me to create file named Ok
