### ISSUE TITLE
Exception in Product-Recommendation-Matrix Factorization sample

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/machinelearning-samples#166]
Exception in Product Recommendation-Matrix Factorization
This sample needs to be fixed. It is currently throwing the following exception when running:

System.FormatException
  HResult=0x80131537
  Message=Parsing failed with an exception: Stream reading encountered exception
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Runtime.Data.TextLoader.Cursor.<ParseParallel>d__33.MoveNext()
   at Microsoft.ML.Runtime.Data.TextLoader.Cursor.MoveNextCore()
   at Microsoft.ML.Runtime.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Runtime.Recommender.Internal.SafeTrainingAndModelBuffer.ConstructLabeledNodesFrom(IChannel ch, ICursor cursor, ValueGetter`1 labGetter, ValueGetter`1 rowGetter, ValueGetter`1 colGetter, Int32 rowCount, Int32 colCount)
   at Microsoft.ML.Runtime.Recommender.Internal.SafeTrainingAndModelBuffer.Train(IChannel ch, Int32 rowCount, Int32 colCount, ICursor cursor, ValueGetter`1 labGetter, ValueGetter`1 rowGetter, ValueGetter`1 colGetter)
   at Microsoft.ML.Trainers.MatrixFactorizationTrainer.TrainCore(IChannel ch, RoleMappedData data, RoleMappedData validData)
   at Microsoft.ML.Trainers.MatrixFactorizationTrainer.Train(IDataView trainData, IDataView validationData)
   at ProductRecommender.Program.Main(String[] args) in D:\GitRepos\machinelearning-samples-master\samples\csharp\getting-started\MatrixFactorization_ProductRecommendation\ProductRecommender\Program.cs:line 60

Inner Exception 1:
FormatException: Stream reading encountered exception

Inner Exception 2:
IOException: Could not open file './Data/Amazon0302.txt'. Error is: Could not find a part of the path 'D:\GitRepos\machinelearning-samples-master\samples\csharp\getting-started\MatrixFactorization_ProductRecommendation\ProductRecommender\bin\Debug\netcoreapp2.1\Data\Amazon0302.txt'.

Inner Exception 3:
DirectoryNotFoundException: Could not find a part of the path 'XXXXXXXX\samples\csharp\getting-started\MatrixFactorization_ProductRecommendation\ProductRecommender\bin\Debug\netcoreapp2.1\Data\Amazon0302.txt'.

It also needs to be updated from version 0.8.0-preview-27128-6 to version 0.8

**Comment by prathyusha12345** [comment]
Closing, this is stale
