### ISSUE TITLE
MulticlassClassification_Iris 1.0.0-Preview Fails on model load

### ISSUE THREAD

**Issue by Nozziel** [dotnet/machinelearning-samples#353]
Sample MulticlassClassification Iris **1.0.0-Preview** Fails on model load

**Exception on:**
trainedModel = mlContext.Model.Load(stream, out var modelInputSchema);

**Exception message:**
Couldn't load model: 'TransformerChain\Transform_002\Transform_000\Model'

System.InvalidOperationException
  HResult=0x80131509
  Message=Error during class instantiation
  Source=Microsoft.ML.Core
  StackTrace:
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at MulticlassClassification_Iris.Program.TestSomePredictions(MLContext mlContext) in C:\Users\xxxxx\source\repos\ML 1.0.0 prev samples\samples\csharp\getting-started\MulticlassClassification_Iris\IrisClassification\IrisClassificationConsoleApp\Program.cs:line 100
   at MulticlassClassification_Iris.Program.Main(String[] args) in C:\Users\xxxxx\source\repos\ML 1.0.0 prev samples\samples\csharp\getting-started\MulticlassClassification_Iris\IrisClassification\IrisClassificationConsoleApp\Program.cs:line 36

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
InvalidOperationException: Error during class instantiation

Inner Exception 3:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 4:
InvalidOperationException: Error during class instantiation

Inner Exception 5:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 6:
FormatException: Couldn't load model: 'TransformerChain\Transform_002\Transform_000\Model'

**Comment by prathyusha12345** [comment]
@Nozziel There is bug https://github.com/dotnet/machinelearning/issues/3209  that got fixed in ML.Net 1.0 which we will migrate to in couple of days. This issue is occurring with **SDCANonCalibrated** trainer. Please try using other trainer **SdcaMaximumEntropy** meanwhile. Please let me know if you still face any issue.

**Comment by Nozziel** [comment]
@prathyusha12345  With **SdcaMaximumEntropy** it works as expected.

**Comment by prathyusha12345** [comment]
@Nozziel That's great!!! We also have migrated the samples to **ML.Net 1.0.0-preview**. Please refer to the code here  https://github.com/dotnet/machinelearning-samples if you need.

Closing the issue. Thanks
