### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Microsoft.ML.FastTree, Version=1.0.0.0

### ISSUE THREAD

**Issue by lolsoftware** [dotnet/machinelearning-samples#371]
When running the SalesForecast.Solution -> TestObjectPoolingConsoleApp solution (or the eShopDashboard solution), I am getting the following exception:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.ComponentCatalog.LoadableClassInfo.CreateInstanceCore(Object[] ctorArgs)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes](IHostEnvironment env, Type signatureType, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.Runtime.ComponentCatalog.TryCreateInstance[TRes,TSig](IHostEnvironment env, TRes& result, String name, String options, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModelCore[TRes,TSig](IHostEnvironment env, TRes& result, Object[] extra)
   at Microsoft.ML.ModelLoadContext.TryLoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, Entry ent, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModelOrNull[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelLoadContext.LoadModel[TRes,TSig](IHostEnvironment env, TRes& result, RepositoryReader rep, String dir, Object[] extra)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Common.MLModelEngine`2..ctor(MLContext mlContext, String modelFilePathName, Int32 minPredictionEngineObjectsInPool, Int32 maxPredictionEngineObjectsInPool, Double expirationTime) in d:\machinelearning-samples\samples\csharp\common\MLModelEngine.cs:line 38
   at TestObjectPoolingConsoleApp.Program.Main(String[] args) in d:\machinelearning-samples\samples\csharp\end-to-end-apps\Regression-SalesForecast\src\TestObjectPoolingConsoleApp\Program.cs:line 27

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'Microsoft.ML.FastTree, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Any ideas?

**Comment by prathyusha12345** [comment]
Fixed the issue in the commit [here](https://github.com/dotnet/machinelearning-samples/commit/82ff06d711b4223380252b843ef7e90634626612) by adding nuget package  Microsoft.ML.FastTree 1.0.0-preview.

Please try adding the nuget package. Closing the issue. Please reopen if you encounter any issue. Thanks 👍
