### ISSUE TITLE
F# samples problems in Visual Studio 2017 15.7.6

### ISSUE THREAD

**Issue by nightroman** [dotnet/machinelearning-samples#40]
On opening *samples\fsharp\getting-started\GettingStarted.sln* a message box is shown:

    Internal error: Critical capabilities changes were detected without any change
    made to the project 'Regression_TaxiFarePrediction.fsproj', and forces the
    project to be reloaded.  Potential capabilities involved: 'FSharp'.

After that the solution and its projects are loaded with the following oddities:

- In the solution explorer projects miss their `Dependencies`.
- Building gives errors like:

```
    1>------ Build started: Project: Regression_TaxiFarePrediction, Configuration: Debug Any CPU ------
    1>C:\Program Files\dotnet\sdk\2.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5):
    error : Assets file 'C:\-\ML\machinelearning-samples\samples\fsharp\getting-started\Regression_TaxiFarePrediction\obj\project.assets.json' not found.
    Run a NuGet package restore to generate this file.
    1>Done building project "Regression_TaxiFarePrediction.fsproj" -- FAILED.
```

Restoring and building from the command line using `dotnet` works fine.

**Comment by vipero07** [comment]
I've seen the same issue and this is the project fault failure I get in my diagnostic log.

```
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project 'Regression_TaxiFarePrediction.fsproj', and forces the project to be reloaded.  Potential capabilities involved: 'FSharp'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.<RequestReloadForIncompatibleCapabilitiesAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Internal error: Critical capabilities changes were detected without any change made to the project 'Regression_TaxiFarePrediction.fsproj', and forces the project to be reloaded.  Potential capabilities involved: 'FSharp'.
   at Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesRequirementsService.<RequestReloadForIncompatibleCapabilitiesAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```
