### ISSUE TITLE
Price prediction build model issue

### ISSUE THREAD

**Issue by JasonCSharpCoder** [dotnet/machinelearning-samples#443]
Hi, as document guides, I use the price prediction,when train data, errors as below
Inferring Columns ...
Creating Data loader ...
Loading data ...
Exploring multiple ML algorithms and settings to find you the best model for ML task: regression
For further learning check: https://aka.ms/mlnet-cli
|     Trainer                             RSquared Absolute-loss Squared-loss RMS-loss  Duration #Iteration      |
[Source=AutoML, Kind=Trace] Channel started
Exception occured while exploring pipelines:
Provided label column 'vendor_id' was of type String, but only type Single is allowed.
System.ArgumentException: Provided label column 'vendor_id' was of type String, but only type Single is allowed.
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()
Please see the log file for more info.

**Comment by justinormont** [comment]
Try setting `--has-header true` as a parameter.

**Comment by justinormont** [comment]
Related: https://github.com/dotnet/machinelearning-automl/issues/410 ("Feature : header detection capabilities")
