### ISSUE TITLE
Installation of ML.net modelbuilder failed but i have VS2017

### ISSUE THREAD

**Issue by petervander** [dotnet/machinelearning-samples#451]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

I have Visual Studio Community 2017 version 15.8.1 so this should work but the installation doesn't seem to find it,

Install gives error:  "This extension is not installable on an currently installed products"

last part of error log says:
13/05/2019 11:00:36 PM - 	Supported Products : 
13/05/2019 11:00:36 PM - 		Microsoft.VisualStudio.Community
13/05/2019 11:00:36 PM - 			Version : [15.0,17.0)
13/05/2019 11:00:36 PM - 		Microsoft.VisualStudio.Enterprise
13/05/2019 11:00:36 PM - 			Version : [15.0,17.0)
13/05/2019 11:00:36 PM - 		Microsoft.VisualStudio.Pro
13/05/2019 11:00:36 PM - 			Version : [15.0,17.0)
13/05/2019 11:00:36 PM - 
13/05/2019 11:00:36 PM - 	References      : 
13/05/2019 11:00:36 PM - 
13/05/2019 11:00:36 PM - Searching for applicable products...
13/05/2019 11:00:37 PM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
13/05/2019 11:00:37 PM - Found installed product - Microsoft Visual C++ Express 2010
13/05/2019 11:00:37 PM - Found installed product - Microsoft Visual Studio Community 2013
13/05/2019 11:00:37 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
13/05/2019 11:00:37 PM - Found installed product - Global Location
13/05/2019 11:00:37 PM - Found installed product - ssms
13/05/2019 11:00:37 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by mcerdeira** [comment]
Same problem, how do you resolved it?

**Comment by petervander** [comment]
Still haven't resilved this! Havent used the modelbuilder as a result

**Comment by rustd** [comment]
This is being tracked here https://github.com/dotnet/machinelearning-modelbuilder/issues/43 
@petervander can you try the latest extension which was released 2 days ago.
@JakeRadMSFT can you please follow-up with @petervander

**Comment by JakeRadMSFT** [comment]
Hello,
What versions number of Visual Studio 2017 do you have installed?

Model Builder can be installed on Visual Studio 2017 version 15.9.12 and later.
