### ISSUE TITLE
i chage TinyYolo2_model.onnx to yolov3.onnx in my project ObjectDetection .BUT ERROR:

### ISSUE THREAD

**Issue by vc815** [dotnet/machinelearning-samples#463]
System.InvalidOperationException
  HResult=0x80131509
  Message=Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from C:\Users\Administrator\Desktop\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\bin\Debug\netcoreapp2.2\../../../assets\Model\yolov3.onnx failed:Node:TFNodes/yolo_evaluation_layer_1/strided_slice Node (TFNodes/yolo_evaluation_layer_1/strided_slice) has input size 5 not in range [min=1, max=1].
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 83
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 31
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
  Source=Microsoft.ML.OnnxTransformer
  StackTrace:
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at ObjectDetection.OnnxModelScorer.LoadModel(String imagesFolder, String modelLocation) in C:\Users\Administrator\Desktop\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\OnnxModelScorer.cs:line 62
   at ObjectDetection.OnnxModelScorer.Score() in C:\Users\Administrator\Desktop\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\OnnxModelScorer.cs:line 48
   at ObjectDetection.Program.Main() in C:\Users\Administrator\Desktop\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\Program.cs:line 21

内部异常 1:
OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from C:\Users\Administrator\Desktop\machinelearning-samples-master\samples\csharp\getting-started\DeepLearning_ObjectDetection_Onnx\ObjectDetectionConsoleApp\bin\Debug\netcoreapp2.2\../../../assets\Model\yolov3.onnx failed:Node:TFNodes/yolo_evaluation_layer_1/strided_slice Node (TFNodes/yolo_evaluation_layer_1/strided_slice) has input size 5 not in range [min=1, max=1].

 HOW TO  FIX ZHIS error   ? thinks!

**Comment by wschin** [comment]
This happens probably because ML.NET's ONNX engine is not following the latest ONNX standard. We will get it fixed by the end of next month. In the meanwhile, you can try to downgrade your model using ONNX version converter (see the document [here](https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md)). You probably want to try `target_version=7` when calling that converter.

**Comment by CESARDELATORRE** [comment]
@vc815 - Can you open this issue at the ML.NET repo issues sinxe it looks like it is related to the platform instead the samples?

Here: https://github.com/dotnet/machinelearning/issues 

Thanks! 👍
