### ISSUE TITLE
Microsoft.ML.Transforms.TensorFlow.TFException

### ISSUE THREAD

**Issue by developervariety** [dotnet/machinelearning-samples#468]
This is my class.

```csharp
public interface IModelScorer
    {
        PredictionEngine<ImageNetData, ImageNetPrediction> CreatePredictionFunction();
        ImageNetLabelPrediction PredictLabelWithProbability(string imageFilePath);
    }
    
    public class ModelScorer : IModelScorer
    {
        private readonly string _dataLocation;
        private readonly string _imagesFolder;
        private readonly string _modelLocation;
        private readonly string _labelsLocation;
        private readonly MLContext _mlContext;
        private static string _imageReal = nameof(_imageReal);
        
        private readonly PredictionEngine<ImageNetData, ImageNetPrediction> _predictionFunction;
        public PredictionEngine<ImageNetData, ImageNetPrediction> PredictionFunction => _predictionFunction;

        public ModelScorer(string dataLocation, string imagesFolder, string modelLocation, string labelsLocation)
        {
            _dataLocation = dataLocation;
            _imagesFolder = imagesFolder;
            _modelLocation = modelLocation;
            _labelsLocation = labelsLocation;
            _mlContext = new MLContext();
            
            _predictionFunction = CreatePredictionFunction();
        }

        public struct ImageNetSettings
        {
            public const int ImageHeight = 224;
            public const int ImageWidth = 224;
            public const float Mean = 117;
            public const bool ChannelsLast = true;
        }

        public struct InceptionSettings
        {
            public const string InputTensorName = "Placeholder";
            public const string OutputTensorName = "loss";
        }

        public void Score(string imagePath)
        {

            ImageNetLabelPrediction prediction = PredictLabelWithProbability(imagePath);

            Console.WriteLine(prediction.PredictedLabel);
        }

        public PredictionEngine<ImageNetData, ImageNetPrediction> CreatePredictionFunction()
        {            
            Console.WriteLine($"Model location: {_modelLocation}");
            Console.WriteLine($"Images folder: {_imagesFolder}");
            Console.WriteLine($"Training file: {_dataLocation}");
            Console.WriteLine($"Default parameters: image size=({ImageNetSettings.ImageWidth},{ImageNetSettings.ImageHeight}), image mean: {ImageNetSettings.Mean}");

            IDataView dataView = CreateDataView();

            EstimatorChain<TensorFlowTransformer> pipeline = _mlContext.Transforms.LoadImages("Placeholder", _imagesFolder, nameof(ImageNetData.ImagePath))
                .Append(_mlContext.Transforms.ResizeImages("Placeholder", ImageNetSettings.ImageWidth, ImageNetSettings.ImageHeight, "Placeholder"))
                .Append(_mlContext.Transforms.ExtractPixels("Placeholder", interleavePixelColors: ImageNetSettings.ChannelsLast, offsetImage: ImageNetSettings.Mean))
                .Append(_mlContext.Model.LoadTensorFlowModel(_modelLocation).
                    ScoreTensorFlowModel(new[] { "loss" },
                        new[] { "Placeholder" }, true));
                        
            ITransformer model = pipeline.Fit(dataView);

            return _mlContext.Model.CreatePredictionEngine<ImageNetData, ImageNetPrediction>(model);
        }

        ImageNetLabelPrediction IModelScorer.PredictLabelWithProbability(string imageFilePath)
        {
            return PredictLabelWithProbability(imageFilePath);
        }

        protected ImageNetLabelPrediction PredictLabelWithProbability(string imageFile)
        {
            try
            {
                string[] labels = ReadLabels(_labelsLocation);

                ImageNetData imageInputData = new ImageNetData { ImagePath = imageFile };
                float[] imageLabelPredictions;
        
                lock (_predictionFunction)
                {
                    imageLabelPredictions = _predictionFunction.Predict(imageInputData).PredictedLabels;
                }

                ImageNetLabelPrediction imageBestLabelPrediction = new ImageNetLabelPrediction
                {
                    ImagePath = imageInputData.ImagePath
                };

                (imageBestLabelPrediction.PredictedLabel, imageBestLabelPrediction.Probability) = GetBestLabel(labels, imageLabelPredictions);

                return imageBestLabelPrediction;

            }
            catch (Exception e)
            {
                throw e;
            } 
        }
        
        private IDataView CreateDataView()
        {
            List<ImageNetData> list = new List<ImageNetData>();
            IEnumerable<ImageNetData> enumerableData = list;
            
            IDataView dv = _mlContext.Data.LoadFromEnumerable(enumerableData);
            return dv;
        }
    }
```

*Part of the exception*
```csharp
Unhandled Exception: Microsoft.ML.Transforms.TensorFlow.TFException: The first dimension of paddings must be the rank of inputs[4,2] [1,1,224,224,3]
         [[{{node conv0/pad_size}} = Pad[T=DT_FLOAT, Tpaddings=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](data_bn/data_bn/add_1, block2_0_conv3/pad_size/paddings)]]
   at Rcd.Core.ML.ModelScorer.PredictLabelWithProbability(String imageFile) in REDACTED:line 114
   at Core.ML.ModelScorer.Score(String imagePath) in REDACTED:line 57
```

**Comment by developervariety** [comment]
I should also include I am using a custom model exported from Custom Vision (Azure).

**Comment by prathyusha12345** [comment]
Can you share the model location to try once from my end

**Comment by developervariety** [comment]
Yes, @prathyusha12345.

Here's a Google Drive link.
https://drive.google.com/open?id=11Cvdku7IybhOA2vAqfcE86UcQeqhoEme

**Comment by prathyusha12345** [comment]
I have tried the custom model you have provided. While prediction, The model is not able to predict any label. The imageLabelPredictions value after executing below statement is null. Not sure why model is not able to predict.

` imageLabelPredictions = _predictionFunction.Predict(imageInputData).PredictedLabels;`

I have created an issue in MachinLearning Repo here https://github.com/dotnet/machinelearning/issues/3751

**Comment by developervariety** [comment]
iirc this works on ML v0.7

My project requires the latest version otherwise I would use v0.7, but thank you for your help.

**Comment by developervariety** [comment]
Switched to ML v0.7 for testing, and it's "working" but it has one issue. It continues giving me the same model.

Used the example from @CESARDELATORRE's web API, same model.

**Comment by CESARDELATORRE** [comment]
We’ll look into this.
Btw, the model trained with Custom Vision from the WebAPI sample was able to just classify between two kinds of chairs. It was lacking a “null” or not applicable object, though, which should be implemented when training with Custom Vision.

**Comment by developervariety** [comment]
I used my own model with your example since it's the only example that helped and explained the most.

**Comment by developervariety** [comment]
**Update with the new model**

Same result, returns the same model when it shouldn't be. If anyone would like me to provide some images to test with that model just let me know.

The model works fine on Azure Prediction API, but when I export it to TensorFlow and use it on ML v0.7 it doesn't do the expected outcome.

GIF of it in action:
https://i.imgur.com/Vm5zpQz.gifv

**Comment by zeahmed** [comment]
@developervariety, please set `addBatchDimensionInput: false` because this model has input with fully specified shape [?, 224, 224, 3] which is against inception model which does not have fully specified shape for the input.

**Comment by CESARDELATORRE** [comment]
@developervariety - Right, I tested the sample using the TensorFlow model generated with Cognitive Service Custom Vision and it works good by setting to `addBatchDimensionInput: false`

Closing this issue. Thanks for raising it up! 👍
