### ISSUE TITLE
I have Visual Studio Enterprise version 15.9.7 and the ML extension says could not find a suitable version of Visual Studio.

### ISSUE THREAD

**Issue by krravi55** [dotnet/machinelearning-samples#538]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by krravi55** [comment]
This is the installation Log,

6/27/2019 10:20:59 AM - Microsoft VSIX Installer
6/27/2019 10:20:59 AM - -------------------------------------------
6/27/2019 10:20:59 AM - vsixinstaller.exe version:
6/27/2019 10:20:59 AM - 15.9.3041
6/27/2019 10:20:59 AM - -------------------------------------------
6/27/2019 10:20:59 AM - Command line parameters:
6/27/2019 10:20:59 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ravi.rajangam\Downloads\MLNET_Model_Builder.vsix
6/27/2019 10:20:59 AM - -------------------------------------------
6/27/2019 10:20:59 AM - Microsoft VSIX Installer
6/27/2019 10:20:59 AM - -------------------------------------------
6/27/2019 10:21:10 AM - Initializing Install...
6/27/2019 10:21:11 AM - Extension Details...
6/27/2019 10:21:11 AM - 	Identifier         : FE96D051-645F-4309-AE99-107A776B0DA2
6/27/2019 10:21:11 AM - 	Name               : ML.NET Model Builder (Preview)
6/27/2019 10:21:11 AM - 	Author             : Microsoft
6/27/2019 10:21:11 AM - 	Version            : 16.0.1906.701
6/27/2019 10:21:11 AM - 	Description        : Simple UI tool to build custom machine learning models.
6/27/2019 10:21:11 AM - 	Locale             : en-US
6/27/2019 10:21:11 AM - 	MoreInfoURL        : 
6/27/2019 10:21:11 AM - 	InstalledByMSI     : False
6/27/2019 10:21:11 AM - 	SupportedFrameworkVersionRange : [4.5,)
6/27/2019 10:21:11 AM - 
6/27/2019 10:21:15 AM - 	SignatureState     : ValidSignature
6/27/2019 10:21:15 AM - 	SignedBy           : Microsoft Corporation
6/27/2019 10:21:15 AM - 	Certificate Info   : 
6/27/2019 10:21:15 AM - 		-------------------------------------------------------
6/27/2019 10:21:15 AM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/27/2019 10:21:15 AM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/27/2019 10:21:15 AM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
6/27/2019 10:21:15 AM - 		[Not Before]    : 9/6/2018 4:00:30 PM
6/27/2019 10:21:15 AM - 		[Not After]     : 9/6/2019 4:00:30 PM
6/27/2019 10:21:15 AM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - 	Supported Products : 
6/27/2019 10:21:15 AM - 		Microsoft.VisualStudio.Community
6/27/2019 10:21:15 AM - 			Version : [15.0.28307.665,17.0)
6/27/2019 10:21:15 AM - 		Microsoft.VisualStudio.Enterprise
6/27/2019 10:21:15 AM - 			Version : [15.0.28307.665,17.0)
6/27/2019 10:21:15 AM - 		Microsoft.VisualStudio.Pro
6/27/2019 10:21:15 AM - 			Version : [15.0.28307.665,17.0)
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - 	References         : 
6/27/2019 10:21:15 AM - 	Prerequisites      : 
6/27/2019 10:21:15 AM - 		-------------------------------------------------------
6/27/2019 10:21:15 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/27/2019 10:21:15 AM - 		Name         : Visual Studio core editor
6/27/2019 10:21:15 AM - 		Version      : [15.0,17.0)
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - 		-------------------------------------------------------
6/27/2019 10:21:15 AM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
6/27/2019 10:21:15 AM - 		Name         : .NET Core cross-platform development
6/27/2019 10:21:15 AM - 		Version      : [15.0,17.0)
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - 		-------------------------------------------------------
6/27/2019 10:21:15 AM - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
6/27/2019 10:21:15 AM - 		Name         : .NET Core 2.1 development tools
6/27/2019 10:21:15 AM - 		Version      : [15.0,17.0)
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - Signature Details...
6/27/2019 10:21:15 AM - 	Extension is signed with a valid signature.
6/27/2019 10:21:15 AM - 
6/27/2019 10:21:15 AM - Searching for applicable products...
6/27/2019 10:21:15 AM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
6/27/2019 10:21:15 AM - Found installed product - Microsoft Visual Studio Professional 2015
6/27/2019 10:21:15 AM - Found installed product - Microsoft Visual Studio Community 2015
6/27/2019 10:21:15 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/27/2019 10:21:15 AM - Found installed product - Global Location
6/27/2019 10:21:15 AM - Found installed product - ssms
6/27/2019 10:21:15 AM - Found installed product - Visual Studio Enterprise 2017
6/27/2019 10:21:15 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
