### ISSUE TITLE
Unable to install VSIX Installer extension

### ISSUE THREAD

**Issue by ankushmadankar** [dotnet/machinelearning-samples#588]
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

26/07/2019 01:46:53 PM - Microsoft VSIX Installer
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - vsixinstaller.exe version:
26/07/2019 01:46:53 PM - 15.9.3041
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - Command line parameters:
26/07/2019 01:46:53 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\z003v57f\Downloads\MLNET_Model_Builder.vsix
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:53 PM - Microsoft VSIX Installer
26/07/2019 01:46:53 PM - -------------------------------------------
26/07/2019 01:46:54 PM - Initializing Install...
26/07/2019 01:46:54 PM - Extension Details...
26/07/2019 01:46:54 PM - 	Identifier         : FE96D051-645F-4309-AE99-107A776B0DA2
26/07/2019 01:46:54 PM - 	Name               : ML.NET Model Builder (Preview)
26/07/2019 01:46:54 PM - 	Author             : Microsoft
26/07/2019 01:46:54 PM - 	Version            : 16.0.1907.1703
26/07/2019 01:46:54 PM - 	Description        : Simple UI tool to build custom machine learning models.
26/07/2019 01:46:54 PM - 	Locale             : en-US
26/07/2019 01:46:54 PM - 	MoreInfoURL        : 
26/07/2019 01:46:54 PM - 	InstalledByMSI     : False
26/07/2019 01:46:54 PM - 	SupportedFrameworkVersionRange : [4.5,)
26/07/2019 01:46:54 PM - 
26/07/2019 01:46:58 PM - 	SignatureState     : ValidSignature
26/07/2019 01:46:58 PM - 	SignedBy           : Microsoft Corporation
26/07/2019 01:46:58 PM - 	Certificate Info   : 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
26/07/2019 01:46:58 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
26/07/2019 01:46:58 PM - 		[Serial Number] : 330000026ECE6AE5984BFC96A900000000026E
26/07/2019 01:46:58 PM - 		[Not Before]    : 07/09/2018 02:30:30 AM
26/07/2019 01:46:58 PM - 		[Not After]     : 07/09/2019 02:30:30 AM
26/07/2019 01:46:58 PM - 		[Thumbprint]    : 99B6246883B4B32EA59AE18B36945D205A876800
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 	Supported Products : 
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Community
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Enterprise
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 		Microsoft.VisualStudio.Pro
26/07/2019 01:46:58 PM - 			Version : [15.0.28307.665,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 	References         : 
26/07/2019 01:46:58 PM - 	Prerequisites      : 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
26/07/2019 01:46:58 PM - 		Name         : Visual Studio core editor
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.VisualStudio.Workload.NetCoreTools
26/07/2019 01:46:58 PM - 		Name         : .NET Core cross-platform development
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - 		-------------------------------------------------------
26/07/2019 01:46:58 PM - 		Identifier   : Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.1
26/07/2019 01:46:58 PM - 		Name         : .NET Core 2.1 development tools
26/07/2019 01:46:58 PM - 		Version      : [15.0,17.0)
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - Signature Details...
26/07/2019 01:46:58 PM - 	Extension is signed with a valid signature.
26/07/2019 01:46:58 PM - 
26/07/2019 01:46:58 PM - Searching for applicable products...
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio Premium 2012 
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio Professional 2012
26/07/2019 01:46:58 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
26/07/2019 01:46:58 PM - Found installed product - Global Location
26/07/2019 01:46:58 PM - Found installed product - Visual Studio Enterprise 2017
26/07/2019 01:46:58 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by bamurtaugh** [comment]
Hi @ankushmadankar - it appears your issue relates to Model Builder rather than ML.NET samples. In that case, your issue would be better-suited for the Model Builder repo: https://github.com/dotnet/machinelearning-modelbuilder/issues. Please let me know if you are having any issues with the samples/samples repo itself!
