### ISSUE TITLE
Cannot find model.zip

### ISSUE THREAD

**Issue by van-tienhoang** [dotnet/machinelearning-samples#643]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: macos

Error: when `dotnet run`

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/Users/xxx/Downloads/tmp/myMLApp/consumeModelApp/MLModel.zip'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at consumeModelApp.Program.ConsumeModel() in /Users/van/Downloads/tmp/myMLApp/consumeModelApp/Program.cs:line 19
   at consumeModelApp.Program.Main(String[] args) in /Users/van/Downloads/tmp/myMLApp/consumeModelApp/Program.cs:line 11

**Comment by bamurtaugh** [comment]
When you say no extra setting, you mean that you did complete those 3 steps successfully?

**Comment by van-tienhoang** [comment]
yes, and basically, i just copied the command and ran it in sequences.
