### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by BeginTry** [dotnet/machinelearning-samples#679]
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: Windows 10 Pro

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

```
namespace ML_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            // Add input data
            var input = new ModelInput();
            input.TweetText = "Dave, that is really cool.";

            // Load model and predict output of sample data
            ModelOutput result = ConsumeModel.Predict(input);

            Console.WriteLine(result.Prediction.ToString());
            Console.ReadKey();
        }
    }
}
```

<pre>
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Data.IO.CodecFactory..ctor(IHostEnvironment env, MemoryStreamPool memPool)
   at Microsoft.ML.Data.IO.BinaryLoader..ctor(Arguments args, IHost host, Stream stream, Boolean leaveOpen)
   at Microsoft.ML.ModelOperationsCatalog.Load(Stream stream, DataViewSchema& inputSchema)
   at Microsoft.ML.ModelOperationsCatalog.Load(String filePath, DataViewSchema& inputSchema)
   at ML_TestML.Model.ConsumeModel.Predict(ModelInput input) in C:\Users\Dave\Documents\Visual Studio 2017\Projects\ML_Test\ML_TestML.Model\ConsumeModel.cs:line 24
   at ML_Test.Program.Main(String[] args) in C:\Users\Dave\Documents\Visual Studio 2017\Projects\ML_Test\ML_Test\Program.cs:line 20
</pre>

![image](https://user-images.githubusercontent.com/27367041/66280029-c03b1200-e882-11e9-8fd9-9b1399b0540a.png)
![image](https://user-images.githubusercontent.com/27367041/66280185-86b6d680-e883-11e9-9e1b-78e81b4bb131.png)

**Comment by BeginTry** [comment]
FWIW, I can duplicate this issue on a second machine.

**Comment by BeginTry** [comment]
Note: the project type I chose was Console App (.NET Framework).
If I change the project type to Console App (.NET Core), the issue does not occur.
Sorry for the trouble...Closing this issue.
