### ISSUE TITLE
The size of input lines is not consistent

### ISSUE THREAD

**Issue by bartosz-wozniak-lx** [dotnet/machinelearning-samples#717]
I'm getting the following exception: 
System.ArgumentOutOfRangeException: The size of input lines is not consistent
while I'm trying tu run sample ImageClassification.Train.

This occurs in line "ITransformer trainedModel = pipeline.Fit(trainDataView);"

Is there any fix or workaround, please?

**Comment by CESARDELATORRE** [comment]
Can you point to the exact sample URL you are using when having this issue?

**Comment by bartosz-wozniak-lx** [comment]
Yes, of course: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training

**Comment by thoj** [comment]
Same issue here with the sample above. If I switch to the resnet arch I don't get this error but i get this output:
```
Saver not created because there are no variables in the graph to restore
*** Training the image classification model with DNN Transfer Learning on top of the selected pre-trained model/architecture ***
Training with transfer learning took: 0 seconds
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   1, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   2, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   3, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   4, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   5, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   6, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   7, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   8, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   9, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  10, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  11, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  12, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  13, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  14, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  15, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  16, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  17, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  18, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  19, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  20, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  21, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  22, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  23, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  24, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  25, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  26, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  27, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  28, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  29, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  30, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  31, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  32, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  33, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  34, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  35, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  36, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  37, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  38, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  39, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  40, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  41, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  42, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  43, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  44, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  45, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  46, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  47, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  48, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  49, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  50, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  51, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  52, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  53, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  54, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  55, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  56, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  57, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  58, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  59, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  60, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  61, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  62, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  63, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  64, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  65, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  66, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  67, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  68, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  69, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  70, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  71, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  72, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  73, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  74, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  75, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  76, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  77, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  78, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  79, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  80, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  81, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  82, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  83, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  84, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  85, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  86, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  87, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  88, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  89, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  90, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  91, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  92, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  93, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  94, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  95, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  96, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  97, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  98, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  99, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 100, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 101, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 102, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 103, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 104, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 105, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 106, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 107, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 108, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 109, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 110, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 111, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 112, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 113, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 114, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 115, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 116, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 117, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 118, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 119, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 120, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 121, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 122, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 123, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 124, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 125, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 126, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 127, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 128, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 129, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 130, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 131, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 132, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 133, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 134, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 135, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 136, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 137, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 138, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 139, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 140, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 141, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 142, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 143, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 144, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 145, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 146, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 147, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 148, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 149, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 150, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 151, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 152, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 153, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 154, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 155, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 156, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 157, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 158, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 159, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 160, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 161, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 162, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 163, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 164, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 165, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 166, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 167, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 168, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 169, Image Name:
Phase: Bottleneck Computation, Dataset used:      Train, Image Index: 170, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   1, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   2, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   3, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   4, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   5, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   6, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   7, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   8, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:   9, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  10, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  11, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  12, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  13, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  14, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  15, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  16, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  17, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  18, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  19, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  20, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  21, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  22, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  23, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  24, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  25, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  26, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  27, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  28, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  29, Image Name:
Phase: Bottleneck Computation, Dataset used: Validation, Image Index:  30, Image Name:
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   0, Accuracy:  0,4882352, Cross-Entropy: 7,081955E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   0, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   1, Accuracy:  0,4705882, Cross-Entropy: 6,169476E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   1, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   2, Accuracy:  0,5294118, Cross-Entropy: 4,885881E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   2, Accuracy:  0,2666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   3, Accuracy:  0,4764706, Cross-Entropy: 4,958395E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   3, Accuracy:  0,2333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   4, Accuracy:  0,4941176, Cross-Entropy: 5,939554E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   4, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   5, Accuracy:  0,4882352, Cross-Entropy: 5,615148E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   5, Accuracy:          0
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   6, Accuracy:  0,5294118, Cross-Entropy: 5,2967E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   6, Accuracy:        0,3
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   7, Accuracy:  0,5470588, Cross-Entropy: 4,233541E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   7, Accuracy:  0,2666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   8, Accuracy:  0,5235294, Cross-Entropy: 3,271615E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   8, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:   9, Accuracy:  0,5235295, Cross-Entropy: 5,215298E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:   9, Accuracy:  0,1666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  10, Accuracy:  0,5117648, Cross-Entropy: 3,941893E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  10, Accuracy:  0,1666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  11, Accuracy:        0,4, Cross-Entropy: 5,180342E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  11, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  12, Accuracy:  0,4529412, Cross-Entropy: 5,114708E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  12, Accuracy:  0,1333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  13, Accuracy:  0,4823529, Cross-Entropy: 4,743001E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  13, Accuracy:  0,3333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  14, Accuracy:  0,5529412, Cross-Entropy: 4,846893E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  14, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  15, Accuracy:  0,4647059, Cross-Entropy: 5,490917E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  15, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  16, Accuracy:  0,5470588, Cross-Entropy: 4,3319E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  16, Accuracy:  0,2333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  17, Accuracy:  0,5470588, Cross-Entropy: 4,902256E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  17, Accuracy:  0,2666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  18, Accuracy:        0,5, Cross-Entropy: 5,171959E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  18, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  19, Accuracy:  0,5058823, Cross-Entropy: 4,115873E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  19, Accuracy:  0,2666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  20, Accuracy:  0,4941177, Cross-Entropy: 4,859682E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  20, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  21, Accuracy:  0,5117647, Cross-Entropy: 4,510561E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  21, Accuracy:  0,1333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  22, Accuracy:  0,5529411, Cross-Entropy: 4,102768E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  22, Accuracy: 0,06666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  23, Accuracy:  0,5823529, Cross-Entropy: 4,095825E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  23, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  24, Accuracy:   0,517647, Cross-Entropy: 5,17364E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  24, Accuracy:  0,1666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  25, Accuracy:  0,5470588, Cross-Entropy: 4,286019E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  25, Accuracy:        0,1
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  26, Accuracy:        0,5, Cross-Entropy: 4,775265E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  26, Accuracy:  0,1333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  27, Accuracy:  0,5294118, Cross-Entropy: 4,532864E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  27, Accuracy:  0,2666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  28, Accuracy:   0,517647, Cross-Entropy: 4,960942E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  28, Accuracy:        0,3
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  29, Accuracy:  0,5647059, Cross-Entropy: 3,453163E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  29, Accuracy:  0,1333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  30, Accuracy:        0,5, Cross-Entropy: 5,035258E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  30, Accuracy:  0,1333333
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  31, Accuracy:  0,5529411, Cross-Entropy: 4,524144E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  31, Accuracy:        0,2
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  32, Accuracy:  0,5411765, Cross-Entropy: 3,512103E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  32, Accuracy:  0,1666667
Phase: Training, Dataset used:      Train, Batch Processed Count:  17, Epoch:  33, Accuracy:  0,5058823, Cross-Entropy: 4,79253E+12
Phase: Training, Dataset used: Validation, Batch Processed Count:   3, Epoch:  33, Accuracy:        0,2
Saver not created because there are no variables in the graph to restore
Restoring parameters from C:\Users\ThomasJäger\Documents\nectotoolkit\ML\Necto_MLServer\NEctoInceptionTrainer\bin\Debug\netcoreapp2.1\custom_retrained_model_based_on_resnet_v2_101_299.meta
Froze 2 variables.
Converted 2 variables to const ops.
Making predictions in bulk for evaluating model's quality...
************************************************************
*    Metrics for TensorFlow DNN Transfer Learning multi-class classification model
*-----------------------------------------------------------
    AccuracyMacro = 0,25, a value between 0 and 1, the closer to 1, the better
    AccuracyMicro = 0,2333, a value between 0 and 1, the closer to 1, the better
    LogLoss = 26,4797, the closer to 0, the better
    LogLoss for class 1 = 34,5388, the closer to 0, the better
    LogLoss for class 2 = 11,5129, the closer to 0, the better
    LogLoss for class 3 = 25,9041, the closer to 0, the better
    LogLoss for class 4 = 23,0259, the closer to 0, the better
    LogLoss for class 5 = 34,5388, the closer to 0, the better
************************************************************
Predicting and Evaluation took: 16 seconds
```

Seems like the training isn't actually doing anything? Could maybe be related.

Here is the stack trace when trying to use the inception arch:

```System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The size of input lines is not consistent
Parameter name: Source
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Data.TextLoader.Bindings..ctor(TextLoader parent, Column[] cols, IMultiStreamSource headerFile, IMultiStreamSource dataSample) in E:\A\_work\656\s\src\Microsoft.ML.Data\DataLoadSave\Text\TextLoader.cs:line 689
   at Microsoft.ML.Data.TextLoader..ctor(IHostEnvironment env, Options options, IMultiStreamSource dataSample) in E:\A\_work\656\s\src\Microsoft.ML.Data\DataLoadSave\Text\TextLoader.cs:line 1187
   at Microsoft.ML.Transforms.ImageClassificationTransformer.GetShuffledData(String path) in E:\A\_work\656\s\src\Microsoft.ML.Dnn\ImageClassificationTransform.cs:line 300
   at Microsoft.ML.Transforms.ImageClassificationTransformer.TrainAndEvaluateClassificationLayer(String trainBottleneckFilePath, Options options, String validationSetBottleneckFilePath) in E:\A\_work\656\s\src\Microsoft.ML.Dnn\ImageClassificationTransform.cs:line 329
   at Microsoft.ML.Transforms.ImageClassificationTransformer..ctor(IHostEnvironment env, Options options, DnnModel tensorFlowModel, IDataView input) in E:\A\_work\656\s\src\Microsoft.ML.Dnn\ImageClassificationTransform.cs:line 180
   at Microsoft.ML.Transforms.ImageClassificationEstimator.Fit(IDataView input) in E:\A\_work\656\s\src\Microsoft.ML.Dnn\ImageClassificationTransform.cs:line 1520
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input) in E:\A\_work\656\s\src\Microsoft.ML.Data\DataLoadSave\EstimatorChain.cs:line 67
   at ImageClassification.Train.Program.Main() in C:\Users\Tjä\Documents\Xtoolkit\ML\X_MLServer\XInceptionTrainer\Program.cs:line 474

```

**Comment by CESARDELATORRE** [comment]
Adding @codemzs - I'm not able to reproduce it.
Also, we're updating to ML.NET 1.4 to be released in a couple of days. There are some changes in this API (Image Classification). You might want to try the new version soon.

**Comment by codemzs** [comment]
@thoj @bartosz-wozniak-lx What OS are you guys running this sample? and if you can confirm you have not altered the samples at all? or if you have then please provide the *exact* repro steps.

**Comment by ashbhandare** [comment]
In addition, could you add the complete output log, from start to the stack trace? It will be helpful to find out where the failure occurs.

**Comment by ashbhandare** [comment]
One way of reproducing the error that I found is if interrupt the run when  bottleneck values are being calculated, and in the subsequent run, try to reuse bottleneck values. The cached file thus created does not contain the complete dataset. In this case, the error can be resolved by either not reusing the bottleneck values, or deleting the cached files. There could be a different cause for this error as well. @thoj  and @bartosz-wozniak-lx , can you confirm if your repro steps are different from this?

**Comment by bartosz-wozniak-lx** [comment]
@codemzs I am running this sample on Windows 10. I have tried a few different computers. It works perfectly on OSX but does not work on Windows 10. Yes, I can confirm, I have not altered the samples at all. I have just downloaded it and run it.

**Comment by codemzs** [comment]
@bartosz-wozniak-lx thanks! on Windows 10 were you running on dotnet core or framework?

**Comment by bartosz-wozniak-lx** [comment]
I have tried both (Core and framework). None of them worked.

**Comment by codemzs** [comment]
@bartosz-wozniak-lx in your bin folder there should be two “.csv” files that are created after a run of image classification API. Can you please send them here?
